[package]
name = "evadedpi"
version = "0.2.0"
edition = "2024"
authors = ["tazihad <@tazihad>"]
license = "MIT"
repository = "https://github.com/tazihad/evadedpi"
homepage = "https://zihad.com.bd"
description = "Next-generation Deep Packet Inspection (DPI) circumvention tool and cross-platform proxy by tazihad"

[dependencies]
anyhow = "1.0.104"
bytes = "1.12.1"
clap = { version = "4.6.7", features = ["derive"] }
clap_complete = "4.6.11"
colored = "3.1.1"
libc = "0.2.190"
rand = "0.10.3"
reqwest = { version = "0.13.5", features = ["default-tls", "json"] }
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
socket2 = "0.6.5"
tokio = { version = "1.53.2", features = ["full"] }
toml = "1.1.6"
tracing = "0.1.44"
tracing-subscriber = "0.3.23"
